# Generated by Django 2.2.6 on 2019-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='ship_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
