# Generated by Django 2.2.6 on 2020-03-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='ship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Ship'),
        ),
        migrations.CreateModel(
            name='RawPlotStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship_json', models.TextField()),
                ('ship_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawplotstat_primary', to='scraper.Ship')),
                ('ship_secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawplotstat_secondary', to='scraper.Ship')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoxPlotStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship_primary_percentile', models.IntegerField(default=0)),
                ('ship_secondary_neg2sigma', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ship_secondary_pos2sigma', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ship_secondary_q1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ship_secondary_q2', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ship_secondary_median', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ship_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxplotstat_primary', to='scraper.Ship')),
                ('ship_secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxplotstat_secondary', to='scraper.Ship')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
