# Generated by Django 2.2.6 on 2020-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200329_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxplotstat',
            name='ship_secondary_median',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boxplotstat',
            name='ship_secondary_neg2sigma',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boxplotstat',
            name='ship_secondary_pos2sigma',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boxplotstat',
            name='ship_secondary_q1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boxplotstat',
            name='ship_secondary_q2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
