# Generated by Django 2.2.6 on 2019-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20191016_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='ship_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
