# Generated by Django 2.2.6 on 2020-03-31 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200330_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxplotstat',
            old_name='ship_primary_q2',
            new_name='ship_primary_q3',
        ),
        migrations.RenameField(
            model_name='boxplotstat',
            old_name='ship_secondary_q2',
            new_name='ship_secondary_q3',
        ),
    ]
