# Generated by Django 2.2.6 on 2020-03-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20200330_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxplotstat',
            old_name='ship_primary_neg2sigma',
            new_name='ship_primary_5th',
        ),
        migrations.RenameField(
            model_name='boxplotstat',
            old_name='ship_primary_pos2sigma',
            new_name='ship_primary_95th',
        ),
        migrations.RenameField(
            model_name='boxplotstat',
            old_name='ship_secondary_neg2sigma',
            new_name='ship_secondary_5th',
        ),
        migrations.RenameField(
            model_name='boxplotstat',
            old_name='ship_secondary_pos2sigma',
            new_name='ship_secondary_95th',
        ),
    ]
