# Generated by Django 3.0.4 on 2020-03-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200330_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxplotstat',
            name='ship_primary',
        ),
        migrations.RemoveField(
            model_name='boxplotstat',
            name='ship_primary_percentile',
        ),
        migrations.RemoveField(
            model_name='boxplotstat',
            name='ship_secondary',
        ),
        migrations.RemoveField(
            model_name='boxplotstat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rawplotstat',
            name='ship_primary',
        ),
        migrations.RemoveField(
            model_name='rawplotstat',
            name='ship_secondary',
        ),
        migrations.RemoveField(
            model_name='rawplotstat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='boxplotstat',
            name='ship_top_range',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_type', models.IntegerField(choices=[(1, 'Box'), (2, 'Scatter')])),
                ('ship_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_primary', to='scraper.Ship')),
                ('ship_secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_secondary', to='scraper.Ship')),
            ],
        ),
        migrations.AddField(
            model_name='boxplotstat',
            name='plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scraper.Plot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawplotstat',
            name='plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scraper.Plot'),
            preserve_default=False,
        ),
    ]
