# Generated by Django 2.2.6 on 2020-01-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20191024_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wg_user',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='wg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.User', to_field='wg_user'),
        ),
    ]
