# Generated by Django 3.0.4 on 2020-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20200403_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='ship_id',
            new_name='wg_identifier',
        ),
        migrations.RenameField(
            model_name='userstat',
            old_name='ship_id',
            new_name='ship',
        ),
        migrations.AddField(
            model_name='ship',
            name='median_wr',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ship',
            name='playercount',
            field=models.IntegerField(default=0),
        ),
    ]
