# Generated by Django 3.0.4 on 2020-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20200416_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='human_name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
