# Generated by Django 3.0.4 on 2020-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_nation_human_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='economy_type',
            field=models.IntegerField(choices=[(1, 'Techtree'), (2, 'Premium')], default=0),
            preserve_default=False,
        ),
    ]
