# Generated by Django 3.0.4 on 2020-04-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0009_auto_20200414_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('ship1median', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('ship2median', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('ship1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiprelation_primary', to='scraper.Ship')),
                ('ship2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiprelation_secondary', to='scraper.Ship')),
            ],
        ),
    ]
